-- Complete final security fixes for all remaining functions
ALTER FUNCTION get_time_ago(target_time timestamp with time zone) SET search_path TO 'public';
ALTER FUNCTION check_otp_rate_limit(p_email text) SET search_path TO 'public';
ALTER FUNCTION cleanup_expired_rate_limits() SET search_path TO 'public';
ALTER FUNCTION cleanup_old_communication_events() SET search_path TO 'public';
ALTER FUNCTION verify_customer_otp(p_email text, p_otp_code text, p_otp_type text, p_ip_address text) SET search_path TO 'public';
ALTER FUNCTION requeue_failed_welcome_emails() SET search_path TO 'public';
ALTER FUNCTION update_customer_with_validation(p_customer_id uuid, p_name text, p_email text, p_phone text, p_admin_id uuid, p_ip_address inet, p_user_agent text) SET search_path TO 'public';
ALTER FUNCTION validate_admin_invitation() SET search_path TO 'public';
ALTER FUNCTION log_branding_change(p_action text, p_field_name text, p_old_value text, p_new_value text, p_metadata jsonb, p_ip_address inet, p_user_agent text) SET search_path TO 'public';
ALTER FUNCTION handle_admin_invitation_signup() SET search_path TO 'public';
ALTER FUNCTION update_payment_transaction_timestamp() SET search_path TO 'public';
ALTER FUNCTION trigger_order_status_email() SET search_path TO 'public';
ALTER FUNCTION handle_successful_payment(p_reference text, p_paid_at timestamp with time zone, p_gateway_response text, p_fees numeric, p_channel text, p_authorization_code text, p_card_type text, p_last4 text, p_exp_month text, p_exp_year text, p_bank text) SET search_path TO 'public';
ALTER FUNCTION check_customer_operation_rate_limit(p_admin_id uuid, p_operation text, p_limit integer) SET search_path TO 'public';
ALTER FUNCTION check_production_security() SET search_path TO 'public';
ALTER FUNCTION is_admin() SET search_path TO 'public';
ALTER FUNCTION log_api_request(p_endpoint text, p_method text, p_ip_address inet, p_user_agent text, p_request_payload jsonb, p_response_status integer, p_response_time_ms integer, p_customer_id uuid, p_session_id text, p_error_details jsonb) SET search_path TO 'public';
ALTER FUNCTION calculate_brand_consistency_score() SET search_path TO 'public';
ALTER FUNCTION get_active_paystack_config() SET search_path TO 'public';
ALTER FUNCTION trigger_email_processing() SET search_path TO 'public';
ALTER FUNCTION update_transaction_analytics() SET search_path TO 'public';
ALTER FUNCTION trigger_customer_welcome_after_verification() SET search_path TO 'public';
ALTER FUNCTION is_email_suppressed(email_address text) SET search_path TO 'public';
ALTER FUNCTION trigger_order_emails() SET search_path TO 'public';
ALTER FUNCTION validate_admin_invitation_token(token text) SET search_path TO 'public';
ALTER FUNCTION process_email_queue_real_time() SET search_path TO 'public';
ALTER FUNCTION update_customer_addresses_updated_at() SET search_path TO 'public';
ALTER FUNCTION update_customer_preferences_updated_at() SET search_path TO 'public';
ALTER FUNCTION handle_admin_invitation() SET search_path TO 'public';
ALTER FUNCTION instant_email_trigger() SET search_path TO 'public';