-- Insert default notification templates with correct JSON format for variables
INSERT INTO public.notification_templates (template_key, template_name, channel, subject, content, variables) VALUES
('delivery_scheduled', 'Delivery Scheduled', 'both', 'Your delivery has been scheduled', 'Hi {customer_name}, your order #{order_number} has been scheduled for delivery on {delivery_date} between {delivery_time}. Track your order at {tracking_url}', '["customer_name", "order_number", "delivery_date", "delivery_time", "tracking_url"]'),
('out_for_delivery', 'Out for Delivery', 'both', 'Your order is out for delivery', 'Hi {customer_name}, your order #{order_number} is now out for delivery with {driver_name}. Estimated arrival: {estimated_time}', '["customer_name", "order_number", "driver_name", "estimated_time"]'),
('delivery_completed', 'Delivery Completed', 'both', 'Your order has been delivered', 'Hi {customer_name}, your order #{order_number} has been successfully delivered. Thank you for your business!', '["customer_name", "order_number"]'),
('pickup_ready', 'Order Ready for Pickup', 'both', 'Your order is ready for pickup', 'Hi {customer_name}, your order #{order_number} is ready for pickup at {pickup_location}. Pickup hours: {pickup_hours}', '["customer_name", "order_number", "pickup_location", "pickup_hours"]'),
('delivery_delayed', 'Delivery Delayed', 'both', 'Update on your delivery', 'Hi {customer_name}, your order #{order_number} delivery has been delayed. New estimated time: {new_time}. We apologize for the inconvenience.', '["customer_name", "order_number", "new_time"]');

-- Insert default pickup points
INSERT INTO public.pickup_points (name, address, coordinates, contact_phone, operating_hours, instructions) VALUES
('Main Store', '123 Main Street, City Center', '{"lat": 6.5244, "lng": 3.3792}', '+234-800-123-4567', '{"monday": {"open": "08:00", "close": "20:00"}, "tuesday": {"open": "08:00", "close": "20:00"}, "wednesday": {"open": "08:00", "close": "20:00"}, "thursday": {"open": "08:00", "close": "20:00"}, "friday": {"open": "08:00", "close": "20:00"}, "saturday": {"open": "09:00", "close": "18:00"}, "sunday": {"open": "10:00", "close": "16:00"}}', 'Main entrance, ask for pickup counter'),
('Mall Location', '456 Shopping Mall, Level 2', '{"lat": 6.4474, "lng": 3.3903}', '+234-800-123-4568', '{"monday": {"open": "10:00", "close": "22:00"}, "tuesday": {"open": "10:00", "close": "22:00"}, "wednesday": {"open": "10:00", "close": "22:00"}, "thursday": {"open": "10:00", "close": "22:00"}, "friday": {"open": "10:00", "close": "22:00"}, "saturday": {"open": "10:00", "close": "22:00"}, "sunday": {"open": "12:00", "close": "20:00"}}', 'Level 2, near the food court');